name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Your_password123
        ports:
          - 1433:1433
        options: >-
          --health-cmd "./opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1'" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Compile
        run: ./mvnw -B compile
      - name: Unit tests
        run: ./mvnw -B test
      - name: Integration tests
        run: ./mvnw -B failsafe:integration-test failsafe:verify
      - name: Mutation tests
        run: ./mvnw -B org.pitest:pitest-maven:mutationCoverage
      - name: Build Docker image
        run: docker build -t sql-sanitize .
      - name: Start services
        run: docker compose up -d
      - name: Deployment test
        run: curl --retry 10 --retry-connrefused http://localhost:8080/actuator/health
